# Dependencies
markdown:         redcarpet
highlighter:      rb-pygments
gems: [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            pboueke
tagline:          ''
description:      'My personal page. Here you may find some of my thoughts and experiences.'
url:             "https://pboueke.github.io"
baseurl:          /pboueke

author:
  name:           'Pedro Boueke'
  url:            https://github.com/pboueke

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/pboueke
